import { createIcons, Activity, CircleHelp, Flag, Focus, Gauge, Layers, Pause, Play, RotateCcw, Settings2, Shuffle, Timer, X, Zap, Check, Download } from 'lucide';
import { Race, DRIVERS, formatTime } from './simulation.js';
import { RaceScene } from './scene.js';
import './style.css';
const icons={Activity,CircleHelp,Flag,Focus,Gauge,Layers,Pause,Play,RotateCcw,Settings2,Shuffle,Timer,X,Zap,Check,Download};
const icon=name=>`<i data-lucide="${name.replace(/([a-z0-9])([A-Z])/g,'$1-$2').toLowerCase()}"></i>`;
const race=new Race(42);let speed=1,tab='race',key='',configured=false,lastUi=0;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
$('#app').innerHTML=`
 <header class="topbar"><a href="/" class="brand" aria-label="Apex Unknown inicio"><span class="brand-mark">A</span><span>APEX <b>/</b> UNKNOWN</span></a><nav aria-label="Vistas"><button class="nav-button active" data-tab="race" aria-pressed="true">${icon('Flag')} Carrera</button><button class="nav-button" data-tab="results" aria-pressed="false">${icon('Activity')} Resultados</button></nav><div class="header-end"><span id="mode-caption" class="mode-caption">DEMO</span><button class="icon-button" id="configure" aria-label="Configurar Jev" title="Configurar Jev">${icon('Settings2')}</button></div></header>
 <main><section id="race-view" aria-label="Carrera en vivo"><div id="canvas-host"></div><div class="race-status"><span class="dot"></span><span id="live-status">EN PARRILLA</span></div><div class="lap-widget"><span>VUELTA</span><strong id="lap">01 <em>/ 03</em></strong><span id="clock">00:00.00</span></div><div class="track-label"><span>UNKNOWN VALLEY</span><small id="seed-label">SEED 0042</small></div><div class="camera-hint">Arrastrá para girar · Deslizá para acercarte</div><div id="stage-message" role="status"></div><div class="finish-banner" id="finish-overlay" hidden></div>
 <div class="control-dock"><button id="start" class="primary-button">${icon('Play')} <span>Iniciar carrera</span></button><button id="reset" class="icon-button" aria-label="Reiniciar carrera" title="Reiniciar">${icon('RotateCcw')}</button><button id="new-track" class="icon-button" aria-label="Nueva pista" title="Nueva pista">${icon('Shuffle')}</button><span class="control-divider"></span><div class="speed-controls" role="group" aria-label="Velocidad de simulación"><button data-speed="1" class="active" aria-pressed="true">1×</button><button data-speed="2" aria-pressed="false">2×</button><button data-speed="4" aria-pressed="false">4×</button></div><span class="control-divider camera-divider"></span><div class="camera-controls" role="group" aria-label="Cámara"><button data-camera="orbit" class="active icon-button" title="Cámara libre" aria-label="Cámara libre" aria-pressed="true">${icon('Layers')}</button><button data-camera="top" class="icon-button" title="Vista aérea" aria-label="Vista aérea" aria-pressed="false">${icon('Focus')}</button><button data-camera="follow" class="icon-button" title="Seguir piloto" aria-label="Seguir piloto" aria-pressed="false">${icon('Gauge')}</button></div><select id="follow-driver" aria-label="Piloto a seguir" hidden>${DRIVERS.map((d,i)=>`<option value="${i}">${d.name}</option>`).join('')}</select></div></section>
 <section id="results-view" hidden><div class="results-heading"><div><span class="eyebrow">UNKNOWN GRAND PRIX</span><h1>Resultados</h1><p id="results-status"></p></div><button id="export" class="secondary-button">${icon('Download')} <span>Exportar</span></button></div><div class="results-table-wrap"><table><thead><tr><th>Pos.</th><th>Piloto</th><th>Vuelta 1</th><th>Vuelta 2</th><th>Vuelta 3</th><th>Salidas</th><th>Contactos</th><th>Total</th></tr></thead><tbody id="results-body"></tbody></table></div><div class="results-footer"><span id="results-mode">Demostración local</span><span id="results-decisions">0 decisiones</span><span>Tiempos de simulación</span></div></section></main>
 <dialog id="config-dialog"><form method="dialog"><button class="dialog-close icon-button" aria-label="Cerrar">${icon('X')}</button></form><span class="eyebrow">EL CEREBRO DETRÁS DEL VOLANTE</span><h2>Conectá a los pilotos.</h2><p>Usá la demostración local o conectá Jev para que tome las decisiones de los cinco agentes.</p><div class="mode-choices"><button data-mode="demo" class="mode-choice active"><span>${icon('Play')} Demostración</span><small>Políticas locales. Sin llamadas a la API.</small></button><button data-mode="jev" class="mode-choice"><span>${icon('Zap')} Jev · TypeSafe</span><small>Decisiones reales. Consume tu API.</small></button></div><label for="api-key">API key de TypeSafe <span id="key-status">opcional en modo demo</span></label><input type="password" id="api-key" placeholder="Pegá tu API key" autocomplete="off"/><p class="field-note">Se usa sólo en esta sesión y no se guarda en el navegador. También podés configurar TYPESAFE_API_KEY en el servidor.</p><p id="config-error" class="error" role="alert"></p><button id="save-config" class="primary-button">${icon('Check')} Aplicar configuración</button><p class="field-note">Cambiar de modo reinicia la carrera. Las llamadas a Jev se hacen únicamente al iniciar.</p></dialog>
`;
createIcons({icons});
let scene;try{scene=new RaceScene($('#canvas-host'),race);}catch(e){$('#stage-message').textContent='No se pudo iniciar WebGL. Probá en un navegador con aceleración gráfica.';console.error(e);}
const originalFetch=window.fetch.bind(window);window.fetch=(url,options={})=>{if(url==='/api/decide'&&key)options={...options,headers:{...options.headers,Authorization:`Bearer ${key}`}};return originalFetch(url,options);};
fetch('/api/status').then(r=>r.json()).then(d=>{configured=d.configured;$('#key-status').textContent=configured?'configurada en servidor':'opcional en modo demo';}).catch(()=>{});
function refreshIcons(){createIcons({icons});}
function setRunButton(){const el=$('#start');el.innerHTML=`${icon(race.running?'Pause':'Play')} <span>${race.finished?'Volver a correr':race.running?'Pausar':race.time?'Continuar':'Iniciar carrera'}</span>`;refreshIcons();}
function reset(seed=race.seed){race.reset(seed);scene?.build();$('#seed-label').textContent=`SEED ${seed.toString().padStart(4,'0')}`;$('#finish-overlay').hidden=true;setRunButton();updateUi();}
$('#start').onclick=()=>{if(race.finished)reset();race.running=!race.running;race.error='';setRunButton();};
$('#reset').onclick=()=>reset();$('#new-track').onclick=()=>reset(Math.floor(Math.random()*9999)+1);
$$('[data-speed]').forEach(b=>b.onclick=()=>{speed=Number(b.dataset.speed);$$('[data-speed]').forEach(el=>{el.classList.toggle('active',el===b);el.setAttribute('aria-pressed',String(el===b));});});
$$('[data-camera]').forEach(b=>b.onclick=()=>{scene?.setCamera(b.dataset.camera);$('#follow-driver').hidden=b.dataset.camera!=='follow';$$('[data-camera]').forEach(el=>{el.classList.toggle('active',el===b);el.setAttribute('aria-pressed',String(el===b));});});
$('#follow-driver').onchange=e=>{if(scene)scene.selected=Number(e.target.value);};
function showTab(name){tab=name;$('#race-view').hidden=name!=='race';$('#results-view').hidden=name!=='results';document.body.dataset.view=name;$$('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===name);b.setAttribute('aria-pressed',String(b.dataset.tab===name));});if(name==='race')scene?.resize();updateUi();}
$$('[data-tab]').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));
let pendingMode='demo';$('#configure').onclick=()=>{pendingMode=race.mode;$$('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===pendingMode));$('#config-error').textContent='';$('#config-dialog').showModal();};
$$('[data-mode]').forEach(b=>b.onclick=()=>{pendingMode=b.dataset.mode;$$('[data-mode]').forEach(el=>el.classList.toggle('active',el===b));});
$('#save-config').onclick=()=>{const candidate=$('#api-key').value.trim();if(pendingMode==='jev'&&!candidate&&!key&&!configured){$('#config-error').textContent='Agregá una API key para usar Jev o elegí Demostración.';return;}if(candidate)key=candidate;$('#api-key').value='';const changed=race.mode!==pendingMode;race.mode=pendingMode;if(changed)reset();$('#config-dialog').close();$('#mode-caption').textContent=race.mode==='demo'?'DEMO':'JEV';updateUi();};
$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}}));
$('#export').onclick=()=>{const payload={mode:race.mode,seed:race.seed,simulationSeconds:race.time,finished:race.finished,decisions:race.decisions,drivers:race.ranking().map(c=>({name:c.name,lapTimes:c.lapTimes,finishTime:c.finishTime,progress:c.progress,offTrack:c.offTrack,collisions:c.collisions})),events:race.events};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`apex-race-${race.seed}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
function updateUi(){
 const ranking=race.ranking(),leader=ranking[0];
 $('#clock').textContent=formatTime(race.time);$('#lap').innerHTML=`${String(Math.min(leader.lap+1,3)).padStart(2,'0')} <em>/ 03</em>`;
 $('#live-status').textContent=race.finished?'FINALIZADA':race.waiting?'JEV DECIDIENDO':race.running?'EN CARRERA':race.time?'EN PAUSA':'EN PARRILLA';
 $('#stage-message').textContent=race.error||(race.waiting?'Los cinco pilotos están decidiendo…':'');
 if(race.finished&&$('#finish-overlay').hidden){$('#finish-overlay').hidden=false;$('#finish-overlay').innerHTML=`<span class="eyebrow">${leader.finished?'BANDERA A CUADROS':'TIEMPO LÍMITE'}</span><strong style="color:${leader.color}">${leader.name} ${leader.finished?'gana':'lidera'}</strong><span>${leader.finished?formatTime(leader.finishTime):'Clasificación por distancia'}</span><button class="secondary-button" id="see-results">Ver resultados →</button>`;$('#see-results').onclick=()=>showTab('results');}
 if(tab==='results'){$('#results-status').textContent=race.finished?'Carrera finalizada.':race.time?(race.running?'Resultados parciales · Carrera en curso.':'Resultados parciales · Carrera pausada.'):'Iniciá una carrera para comparar a los cinco pilotos.';$('#results-body').innerHTML=ranking.map((c,i)=>`<tr><td class="result-position">${String(i+1).padStart(2,'0')}</td><td><span class="driver-table-dot" style="background:${c.color}"></span><strong>${c.name}</strong><small>${c.style}</small></td>${[0,1,2].map(n=>`<td>${formatTime(c.lapTimes[n])}</td>`).join('')}<td>${c.offTrack}</td><td>${c.collisions}</td><td>${formatTime(c.finishTime)}</td></tr>`).join('');$('#results-mode').textContent=race.mode==='demo'?'Demostración local':'Jev / TypeSafe';$('#results-decisions').textContent=`${race.decisions} decisiones`;}
 const label=race.finished?'Volver a correr':race.running?'Pausar':race.time?'Continuar':'Iniciar carrera';if($('#start span').textContent!==label)setRunButton();
}
updateUi();let last=performance.now();
function frame(now){const dt=(now-last)/1000;last=now;race.tick(dt,speed);if(tab==='race')scene?.render();if(now-lastUi>100){updateUi();lastUi=now;}requestAnimationFrame(frame);}requestAnimationFrame(frame);
window.apexSnapshot=()=>({time:race.time,mode:race.mode,running:race.running,finished:race.finished,waiting:race.waiting,seed:race.seed,decisions:race.decisions,cars:race.cars.map(c=>({name:c.name,x:c.x,z:c.z,speed:c.speed,lap:c.lap,offTrack:c.offTrack,progress:c.progress}))});
if(document.modelContext?.registerTool){
 const lifecycle=new AbortController();
 const register=tool=>{try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
 register({name:'read_race_state',description:'Read the current race standings, simulation time and driver progress.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>window.apexSnapshot()});
 register({name:'set_race_running',description:'Start or pause the current race. Starting in Jev mode sends paid API requests with the configured TypeSafe key.',inputSchema:{type:'object',properties:{running:{type:'boolean'}},required:['running'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||typeof input.running!=='boolean')throw new Error('running must be a boolean');if(race.finished&&input.running)throw new Error('Race finished. Reset using the visible race controls.');race.running=input.running;setRunButton();updateUi();return {running:race.running,time:race.time};}});
 window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}
