import { createIcons, Flag, Focus, Gauge, Layers, Pause, Play, Settings2, Shuffle, X, Check, Download, Plus, Trophy, RotateCcw, Github, Film, Trash2, Pencil } from 'lucide';
import { Race, DRIVERS, makeTrack, formatTime } from './simulation.js';
import { RaceScene } from './scene.js';
import { recordRace, applyReplay } from './recording.js';
import './style.css';
const icons={Flag,Focus,Gauge,Layers,Pause,Play,Settings2,Shuffle,X,Check,Download,Plus,Trophy,RotateCcw,Github,Film,Trash2,Pencil};
const icon=name=>`<i data-lucide="${name.replace(/([a-z0-9])([A-Z])/g,'$1-$2').toLowerCase()}"></i>`;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const randomSeed=()=>crypto.getRandomValues(new Uint32Array(1))[0];
let race=new Race(42),raceId=crypto.randomUUID(),raceName='Sunshine Grand Prix',created=Date.now(),key='',speed=1,sceneError='',saveMessage='',lastUi=0,lastSaveAttempt=0,finishSaved=false,saving=false,saveQueue=Promise.resolve(),saveCount=0,replay=null,live=null,pendingMode='demo';
$('#app').innerHTML=`
<header class="topbar"><a href="/" class="brand" aria-label="JEV Prix home"><span class="brand-mark">${icon('Flag')}</span><span>JEV <em>Prix</em><small>UNKNOWN TRACKS. UNEXPECTED CHAMPIONS.</small></span></a><nav aria-label="Race actions"><button id="new-race" class="nav-button">${icon('Plus')} New race</button><button id="results" class="nav-button">${icon('Trophy')} Results</button></nav><div class="header-end"><span id="mode-caption" class="mode-caption">DEMO</span><button class="icon-button" id="configure" aria-label="Session API key" title="Session API key">${icon('Settings2')}</button><a class="icon-button source-link" href="https://github.com/MartinPuli/f1" target="_blank" rel="noopener" aria-label="Open source on GitHub">${icon('Github')}</a></div></header>
<main><section id="race-view" aria-label="Race circuit"><div id="canvas-host"></div><div class="position-widget"><strong id="position-number"></strong><span id="position-name"></span></div><div class="race-status"><span class="dot"></span><span id="live-status">ON THE GRID</span></div><div class="lap-widget"><span>LAP</span><strong id="lap"></strong><span id="clock">00:00.00</span></div>
<button class="track-label" id="rename-race" aria-label="Rename race"><span id="race-name"></span><small id="seed-label"></small></button><div class="camera-hint">Drag to look around · 1–5 switch driver · C change view</div><div class="speed-widget"><strong id="selected-speed">0</strong><span>km/h</span></div><div id="stage-message" role="status"></div><div class="finish-banner" id="finish-overlay" hidden></div>
<div class="driver-switcher" role="group" aria-label="Choose a driver to follow">${DRIVERS.map((d,i)=>`<button class="pilot-button ${i===4?'active':''}" data-pilot="${i}" style="--pilot:${d.color}" aria-label="Follow ${d.name}" aria-pressed="${i===4}"><span class="pilot-avatar"><b>${d.number}</b></span><span>${d.short}</span></button>`).join('')}</div>
<div id="replay-bar" hidden><span>${icon('Film')} REPLAY</span><input id="replay-seek" type="range" min="0" step="0.1" value="0" aria-label="Replay position"/><output id="replay-time">00:00</output><button id="exit-replay" class="icon-button" aria-label="Exit replay">${icon('X')}</button></div>
<div class="control-dock"><button id="start" class="primary-button">${icon('Play')} <span>Start race</span></button><span class="control-divider"></span><div class="speed-controls" role="group" aria-label="Playback speed"><button data-speed="1" class="active" aria-pressed="true">1×</button><button data-speed="2" aria-pressed="false">2×</button><button data-speed="4" aria-pressed="false">4×</button></div><span class="control-divider"></span><div class="camera-controls" role="group" aria-label="Camera view"><button data-camera="follow" class="active icon-button" title="Follow driver · reset camera" aria-label="Follow driver · reset camera" aria-pressed="true">${icon('Gauge')}</button><button data-camera="orbit" class="icon-button" title="Orbit circuit" aria-label="Orbit circuit" aria-pressed="false">${icon('Layers')}</button><button data-camera="top" class="icon-button" title="Aerial view" aria-label="Aerial view" aria-pressed="false">${icon('Focus')}</button></div></div></section></main>
<dialog id="setup-dialog" aria-labelledby="setup-title"><button class="dialog-close icon-button" data-close aria-label="Close race setup">${icon('X')}</button><span class="eyebrow">FIVE DRIVERS. ZERO TRACK KNOWLEDGE.</span><h2 id="setup-title">Your grid. Your rules.</h2><p>A new circuit. A fresh start. Let your JEVs race.</p><form id="setup-form"><div class="setup-layout"><div class="setup-fields"><label for="race-title">Race name</label><input id="race-title" required maxlength="60" value="Sunshine Grand Prix"/><div class="form-row"><div><label for="race-laps">Laps</label><select id="race-laps">${[1,2,3,4,5].map(n=>`<option ${n===3?'selected':''} value="${n}">${n}</option>`).join('')}</select></div><div><label for="race-seed">Circuit seed</label><input id="race-seed" type="number" min="0" max="4294967295" step="1" required value="42"/></div></div></div><div class="track-preview"><svg id="track-preview" viewBox="-115 -115 230 230" role="img" aria-label="Generated circuit preview"></svg><button type="button" id="randomize" class="secondary-button">${icon('Shuffle')} Surprise me</button><small id="track-length"></small></div></div><div class="mode-choices" role="group" aria-label="Driver mode"><button type="button" data-mode="demo" class="mode-choice active" aria-pressed="true"><span>${icon('Play')} Free demo</span><small>Local drivers. No key needed.</small></button><button type="button" data-mode="jev" class="mode-choice" aria-pressed="false"><span>${icon('Flag')} Race with Jev</span><small>Five agents. Your TypeSafe key.</small></button></div><div id="setup-key-field" hidden><label for="setup-key">TypeSafe API key</label><input type="password" id="setup-key" autocomplete="off" placeholder="Paste your API key"/><p class="field-note">Uses your API credits. Up to 20 requests per simulation second. Your key stays in session memory and is never saved with a race.</p></div><p id="setup-error" class="error" role="alert"></p><button type="submit" class="primary-button wide">${icon('Flag')} <span>Lights out — start race</span></button><p class="setup-footnote">Billions of seed values. Reuse a seed to race the same circuit.<br>Original fan experiment · not affiliated with Formula 1 or the drivers.</p></form></dialog>
<dialog id="results-dialog" aria-labelledby="results-title"><button class="dialog-close icon-button" data-close aria-label="Close results">${icon('X')}</button><span class="eyebrow">THE PADDOCK</span><h2 id="results-title">Race results</h2><div class="result-tabs" role="group" aria-label="Results view"><button class="active" data-results="current" aria-pressed="true">This race</button><button data-results="saved" aria-pressed="false">Saved races</button></div><section id="current-results"><div class="results-heading"><div><h3 id="results-race-name"></h3><p id="results-status"></p></div><button id="export" class="icon-button" aria-label="Download race recording" title="Download race recording">${icon('Download')}</button></div><div class="results-table-wrap"><table><thead><tr><th>POS</th><th>DRIVER</th><th>LAPS</th><th>BEST LAP</th><th>TOTAL</th></tr></thead><tbody id="results-body"></tbody></table></div><div class="results-footer"><span id="results-mode"></span><span id="results-decisions"></span></div><div class="result-actions"><button id="save-race" class="secondary-button">${icon('Check')} Save recording</button><button id="watch-current" class="secondary-button">${icon('Film')} Watch replay</button></div><p id="save-status" class="field-note" role="status"></p></section><section id="saved-results" hidden><p class="field-note">Your latest 50 races. Saved to your account, including recordings you can replay from any camera.</p><div id="archive-list"></div><p id="archive-error" class="error" role="alert"></p><button id="refresh-archive" class="secondary-button">${icon('RotateCcw')} Refresh archive</button></section></dialog>
<dialog id="key-dialog" aria-labelledby="key-title"><button class="dialog-close icon-button" data-close aria-label="Close API settings">${icon('X')}</button><span class="eyebrow">BRING YOUR OWN JEV</span><h2 id="key-title">Your key. Your race.</h2><p>Each visitor uses their own TypeSafe API credits. Demo mode is always free.</p><label for="api-key">TypeSafe API key</label><input type="password" id="api-key" placeholder="Paste your API key" autocomplete="off"/><p id="key-status" class="field-note"></p><p class="field-note">The key is sent through this server to TypeSafe. It stays in memory for this session and is never included in recordings or exports.</p><button id="save-key" class="primary-button">${icon('Check')} Update key</button><button id="clear-key" class="secondary-button">Clear key</button></dialog>
<dialog id="rename-dialog" aria-labelledby="rename-title"><button class="dialog-close icon-button" data-close aria-label="Close rename dialog">${icon('X')}</button><h2 id="rename-title">Name this race.</h2><form id="rename-form"><label for="new-name">Race name</label><input id="new-name" maxlength="60" required/><button class="primary-button" type="submit">${icon('Check')} Save name</button></form></dialog>`;
function refreshIcons(){createIcons({icons});}
refreshIcons();
let scene;try{scene=new RaceScene($('#canvas-host'),race);}catch(e){sceneError='Could not start 3D. Try a browser with hardware acceleration.';console.error(e);}
$('#canvas-host').addEventListener('scene-error',event=>{sceneError=event.detail;race.running=false;updateUi();});
function setCamera(mode){scene?.setCamera(mode);document.body.dataset.camera=mode;$$('[data-camera]').forEach(el=>{const active=el.dataset.camera===mode;el.classList.toggle('active',active);el.setAttribute('aria-pressed',String(active));});}
function selectDriver(i){scene?.selectDriver(i);setCamera('follow');$$('[data-pilot]').forEach(el=>{const active=Number(el.dataset.pilot)===i;el.classList.toggle('active',active);el.setAttribute('aria-pressed',String(active));});updateUi();}
$$('[data-camera]').forEach(b=>b.onclick=()=>setCamera(b.dataset.camera));$$('[data-pilot]').forEach(b=>b.onclick=()=>selectDriver(Number(b.dataset.pilot)));
$$('[data-speed]').forEach(b=>b.onclick=()=>{speed=Number(b.dataset.speed);$$('[data-speed]').forEach(el=>{const active=el===b;el.classList.toggle('active',active);el.setAttribute('aria-pressed',String(active));});});
window.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]')||e.target.closest('input,textarea,select')||e.altKey||e.ctrlKey||e.metaKey)return;if(/^[1-5]$/.test(e.key))selectDriver(Number(e.key)-1);if(e.key.toLowerCase()==='c'){const modes=['follow','orbit','top'];setCamera(modes[(modes.indexOf(scene?.mode)+1)%3]);}});
function pause(){if(replay)replay.playing=false;else {race.running=false;if(race.time>0)saveRace();}updateUi();}
function openModal(id){pause();$(id).showModal();}
$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target!==d)return;const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}));
function updatePreview(){const seed=Number($('#race-seed').value);if(!Number.isInteger(seed)||seed<0||seed>4294967295)return;const track=makeTrack(seed);const points=track.samples.filter((_,i)=>i%9===0).map(p=>`${p.x.toFixed(1)},${p.z.toFixed(1)}`).join(' ');$('#track-preview').innerHTML=`<polygon points="${points}" fill="none" stroke="#d2bba4" stroke-width="13" stroke-linejoin="round"/><polygon points="${points}" fill="none" stroke="#576e74" stroke-width="8" stroke-linejoin="round"/><polygon points="${points}" fill="none" stroke="#fff8e5" stroke-width=".8" stroke-dasharray="2 3"/>`;$('#track-length').textContent=`${Math.round(track.length)} m · Seed ${seed}`;}
function setMode(mode){pendingMode=mode;$$('[data-mode]').forEach(b=>{const active=b.dataset.mode===mode;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});$('#setup-key-field').hidden=mode!=='jev';$('#setup-key').placeholder=key?'Key already connected for this session':'Paste your API key';}
function openSetup(){openModal('#setup-dialog');$('#setup-error').textContent='';$('#race-title').value=race.time?'Untitled Grand Prix':raceName;$('#race-seed').value=randomSeed();$('#race-laps').value=race.limit;setMode(race.mode);updatePreview();}
$('#new-race').onclick=openSetup;$('#randomize').onclick=()=>{$('#race-seed').value=randomSeed();updatePreview();};$('#race-seed').oninput=updatePreview;$$('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));
$('#setup-form').onsubmit=async e=>{e.preventDefault();const candidate=$('#setup-key').value.trim();if(pendingMode==='jev'&&!candidate&&!key){$('#setup-error').textContent='Add a TypeSafe key or choose Free demo.';return;}const name=$('#race-title').value.trim();if(!name){$('#setup-error').textContent='Give your race a name.';return;}if(candidate)key=candidate;$('#setup-key').value='';if(!replay&&race.time)await saveRace();if(live){live.race.generation++;live=null;}race.generation++;replay=null;race=new Race(Number($('#race-seed').value));race.limit=Number($('#race-laps').value);race.mode=pendingMode;race.apiKey=key;raceId=crypto.randomUUID();raceName=name;created=Date.now();finishSaved=false;lastSaveAttempt=0;saveMessage='';scene.race=race;scene.build();race.running=true;$('#setup-dialog').close();$('#finish-overlay').hidden=true;$('#replay-bar').hidden=true;document.body.classList.remove('is-replay');updateUi();};
$('#configure').onclick=()=>{$('#key-status').textContent=key?'A key is connected for this session.':'No key connected.';openModal('#key-dialog');};
$('#save-key').onclick=()=>{const candidate=$('#api-key').value.trim();if(!candidate){$('#key-status').textContent='Paste a key or use Clear key.';return;}key=candidate;race.apiKey=key;if(live)live.race.apiKey=key;$('#api-key').value='';$('#key-dialog').close();};
$('#clear-key').onclick=()=>{key='';race.apiKey='';if(live)live.race.apiKey='';$('#api-key').value='';$('#key-status').textContent='Key cleared. Jev races stay paused until a new key is added.';};
$('#start').onclick=()=>{if(replay){if(replay.time>=replay.record.duration)replay.time=0;replay.playing=!replay.playing;}else if(race.finished){openSetup();return;}else {if(race.mode==='jev'&&!key){$('#configure').click();return;}race.error='';race.running=!race.running;if(!race.running)saveRace();}updateUi();};
$('#rename-race').onclick=()=>{$('#new-name').value=raceName;openModal('#rename-dialog');};
$('#rename-form').onsubmit=e=>{e.preventDefault();const name=$('#new-name').value.trim();if(!name)return;raceName=name;if(replay){replay.record.name=name;if(live?.raceId===replay.record.id)live.raceName=name;queueSave(structuredClone(replay.record));}else if(race.time)saveRace();$('#rename-dialog').close();updateUi();};
async function request(url,opts){const res=await fetch(url,opts);const data=await res.json();if(!res.ok)throw new Error(data.error||'Request failed.');return data;}
async function persist(record){await request('/api/races',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(record)});}
function currentRecord(){return replay?replay.record:recordRace(race,raceId,raceName,created);}
function queueSave(record){saveCount++;saving=true;saveMessage='Saving recording…';saveQueue=saveQueue.then(async()=>{try{await persist(record);saveMessage='Recording saved. Find it in Saved races.';}catch(e){saveMessage=e.message;}finally{saveCount--;saving=saveCount>0;}});return saveQueue;}
async function saveRace(){if(replay||!race.time)return;lastSaveAttempt=race.time;return queueSave(currentRecord());}
$('#save-race').onclick=()=>saveRace();
function download(record){const url=URL.createObjectURL(new Blob([JSON.stringify(record)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`jev-prix-${record.seed}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('#export').onclick=()=>download(currentRecord());
function showResults(which='current'){openModal('#results-dialog');setResultsTab(which);}
function setResultsTab(which){$$('[data-results]').forEach(b=>{const active=b.dataset.results===which;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});$('#current-results').hidden=which!=='current';$('#saved-results').hidden=which!=='saved';if(which==='saved')loadArchive();else updateResults();}
$('#results').onclick=()=>showResults();$$('[data-results]').forEach(b=>b.onclick=()=>setResultsTab(b.dataset.results));$('#refresh-archive').onclick=()=>loadArchive();
async function loadArchive(){const list=$('#archive-list');list.textContent='Loading your races…';$('#archive-error').textContent='';try{const {races}=await request('/api/races');list.innerHTML=races.length?races.map(r=>`<article class="archive-row"><span class="archive-flag">${icon(r.finished?'Flag':'Pause')}</span><div><h3>${esc(r.name)}</h3><p>${esc(new Date(r.created).toLocaleDateString('en-US',{month:'short',day:'numeric'}))} · ${r.mode==='jev'?'Jev':'Demo'} · ${r.laps} ${r.laps===1?'lap':'laps'} · ${r.finished?'Finished':'Saved progress'}</p><small>Seed ${r.seed} · ${formatTime(r.duration)}</small></div><button class="icon-button" data-watch="${r.id}" aria-label="Replay ${esc(r.name)}" title="Watch replay">${icon('Play')}</button><button class="icon-button" data-delete="${r.id}" aria-label="Delete ${esc(r.name)}" title="Delete recording">${icon('Trash2')}</button></article>`).join(''):'<div class="empty-archive"><h3>Your next race belongs here.</h3><p>Start a race. We save progress automatically and keep the finish, too.</p></div>';refreshIcons();$$('[data-watch]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{startReplay(await request(`/api/races/${b.dataset.watch}`));}catch(e){$('#archive-error').textContent=e.message;b.disabled=false;}});$$('[data-delete]').forEach(b=>b.onclick=async()=>{if(b.dataset.confirm!=='yes'){b.dataset.confirm='yes';b.innerHTML='Delete?';b.setAttribute('aria-label','Confirm delete recording');return;}try{await request(`/api/races/${b.dataset.delete}`,{method:'DELETE'});loadArchive();}catch(e){$('#archive-error').textContent=e.message;}});}catch(e){list.textContent='';$('#archive-error').textContent=e.message;}}
function startReplay(record){if(!record.frames?.length)return;if(!replay){race.running=false;live={race,raceId,raceName,created,finishSaved,lastSaveAttempt,saveMessage};}replay={record,time:0,playing:true};race=new Race(record.seed);race.limit=record.laps;raceName=record.name;scene.race=race;scene.build();applyReplay(race,record,0);$('#results-dialog').close();$('#replay-bar').hidden=false;$('#replay-seek').max=record.duration;$('#finish-overlay').hidden=true;document.body.classList.add('is-replay');updateUi();}
$('#watch-current').onclick=()=>startReplay(currentRecord());
$('#exit-replay').onclick=()=>{if(!live)return;({race,raceId,raceName,created,finishSaved,lastSaveAttempt}=live);replay=null;live=null;scene.race=race;scene.build();$('#replay-bar').hidden=true;document.body.classList.remove('is-replay');updateUi();};
$('#replay-seek').oninput=()=>{if(!replay)return;replay.time=Number($('#replay-seek').value);applyReplay(race,replay.record,replay.time);updateUi();};
let resultsRenderKey='';
function updateResults(){const renderKey=[raceId,replay?.record.id,raceName,race.time,saveMessage,saving].join('|');if(renderKey===resultsRenderKey)return;resultsRenderKey=renderKey;const record=currentRecord();$('#results-race-name').textContent=raceName;$('#results-status').textContent=`${record.finished?'Final classification':'Provisional classification'} · Seed ${record.seed} · ${record.laps} ${record.laps===1?'lap':'laps'}`;$('#results-body').innerHTML=record.drivers.map((d,i)=>`<tr><td class="result-position">${i+1}</td><td><span class="driver-table-dot" style="background:${d.color}"></span><strong>${esc(d.name)}</strong></td><td>${d.lapTimes.length}/${record.laps}</td><td>${formatTime(d.lapTimes.length?Math.min(...d.lapTimes):null)}</td><td>${formatTime(d.finishTime)}</td></tr>`).join('');$('#results-mode').textContent=record.mode==='jev'?'Jev · TypeSafe':'Local demo';$('#results-decisions').textContent=`${record.decisions.toLocaleString('en-US')} decisions`;$('#save-status').textContent=saveMessage||'Progress and replays save automatically while you race.';$('#save-race').disabled=saving||!!replay||!race.time;$('#watch-current').disabled=!record.duration;}
function updateUi(){const ranking=race.ranking(),car=race.cars[scene?.selected??4];$('#position-number').innerHTML=`${ranking.indexOf(car)+1}<small>/${DRIVERS.length}</small>`;$('#position-name').textContent=car.name;$('#selected-speed').textContent=Math.round(car.speed*3.6);$('#clock').textContent=formatTime(race.time);$('#lap').innerHTML=`${String(Math.min(car.lap+1,race.limit)).padStart(2,'0')} <em>/ ${String(race.limit).padStart(2,'0')}</em>`;$('#race-name').textContent=raceName;$('#seed-label').textContent=`SEED ${race.seed} · ${replay?'RECORDED RACE':'CLICK TO RENAME'}`;$('#mode-caption').textContent=replay?'REPLAY':race.mode.toUpperCase();$('#live-status').textContent=replay?(replay.playing?'REPLAYING':'REPLAY PAUSED'):race.finished?'CHECKERED FLAG':race.waiting?'JEV IS THINKING':race.running?'LIVE RACE':race.time?'PAUSED':'ON THE GRID';$('#stage-message').textContent=sceneError||race.error||(saveMessage.includes('unavailable')?saveMessage:'')||(race.waiting?'Five drivers. Five decisions…':'');
const label=replay?(replay.playing?'Pause replay':replay.time>=replay.record.duration?'Replay again':'Play replay'):race.finished?'Race again':race.running?'Pause':race.time?'Resume':'Start race';if($('#start span').textContent!==label){$('#start').innerHTML=`${icon((replay?replay.playing:race.running)?'Pause':'Play')} <span>${label}</span>`;refreshIcons();}
if(race.finished&&!replay){if($('#finish-overlay').hidden){$('#finish-overlay').innerHTML=`<span class="finish-label">CHECKERED FLAG</span><strong>${esc(ranking[0].name)} ${ranking[0].finished?'wins!':'leads'}</strong><button class="secondary-button" id="see-results">Results ${icon('Trophy')}</button>`;$('#see-results').onclick=()=>showResults();$('#finish-overlay').hidden=false;refreshIcons();}}else $('#finish-overlay').hidden=true;
if(replay){$('#replay-seek').value=replay.time;$('#replay-time').textContent=formatTime(replay.time);}if($('#results-dialog').open&&!$('#current-results').hidden)updateResults();}
updatePreview();updateUi();let last=performance.now();
function frame(now){const dt=Math.min((now-last)/1000,.1);last=now;if(replay){if(replay.playing){replay.time=Math.min(replay.record.duration,replay.time+dt*speed);if(replay.time>=replay.record.duration)replay.playing=false;}applyReplay(race,replay.record,replay.time);}else {race.tick(dt,speed);if(race.finished&&!finishSaved){race.captureFrame();finishSaved=true;saveRace();}else if(race.running&&race.time-lastSaveAttempt>=15)saveRace();}scene?.render();if(now-lastUi>150){updateUi();lastUi=now;}requestAnimationFrame(frame);}requestAnimationFrame(frame);
document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});
$('#setup-dialog').showModal();
window.jevSnapshot=()=>({time:race.time,mode:replay?'replay':race.mode,running:race.running,finished:race.finished,waiting:race.waiting,seed:race.seed,name:raceName,decisions:race.decisions,cars:race.cars.map(c=>({name:c.name,x:c.x,z:c.z,speed:c.speed,lap:c.lap,progress:c.progress}))});
if(document.modelContext?.registerTool){const lifecycle=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'read_race_state',description:'Read race standings, simulation time and driver progress.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>window.jevSnapshot()},{signal:lifecycle.signal})).catch(()=>{});}catch{}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
